reserved-maps: 1000

Messages:
  Actionbar: '&c%title%'
  CheckingUpdate: '&8&oMineGag: &7Checking for update...'
  FullURL: '&8&oMineGag: &7%url%'
  NoPermission: '&8&oMineGag: &7You don''t have permissions to do this!'
  NotAPlayer: '&8&oMineGag: &7You must be a player in order to execute this command!'
  Reloaded: '&8&oMineGag: &7The plugin has been reloaded!'
  StoppedViewing: '&8&oMineGag: &7You stopped viewing memes :('
  UnknownArgument: '&8&oMineGag: &7The argument you specified is unknown!'
  ViewingMemes: '&8&oMineGag: &7You are now viewing memes!, move to go back to normal. Jump to see the next meme'
