name: MineGag
version: 2.0
main: me.kyllian.minegag.MineGagPlugin
description: View memes in minecraft
api-version: 1.13

commands:
  minegag:
    usage: /<command>
    description: Base command of the plugin
    aliases: [mg]